// Developer Express Code Central Example:
// How to filter a LookUpEdit by multiple columns
// 
// To filter a LookUpEdit by multiple columns, create a LookUpEditStrategy
// descendant and override the UpdateDisplayFilter method where the filter criteria
// is set.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E5210

// Developer Express Code Central Example:
// How to filter a LookUpEdit by multiple columns
// 
// To filter a LookUpEdit by multiple columns, create a LookUpEditStrategy
// descendant and override the CreateDisplayFilterCriteria method where the filter
// criteria is generated
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E5210

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q412037.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
